# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Sun Jul  7 18:30:10 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 772)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_5 = QtGui.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget = QtGui.QWidget(self.splitter_5)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pkgLists = QtGui.QWidget(self.layoutWidget)
        self.pkgLists.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pkgLists.setObjectName("pkgLists")
        self.verticalLayout = QtGui.QVBoxLayout(self.pkgLists)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.pkgLists)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.searchEdit = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.searchEdit.setFont(font)
        self.searchEdit.setInputMask("")
        self.searchEdit.setText("")
        self.searchEdit.setObjectName("searchEdit")
        self.verticalLayout_5.addWidget(self.searchEdit)
        self.karmaCheckBox = QtGui.QCheckBox(self.groupBox)
        self.karmaCheckBox.setObjectName("karmaCheckBox")
        self.verticalLayout_5.addWidget(self.karmaCheckBox)
        self.karmaUsernameEdit = QtGui.QLineEdit(self.groupBox)
        self.karmaUsernameEdit.setDragEnabled(False)
        self.karmaUsernameEdit.setObjectName("karmaUsernameEdit")
        self.verticalLayout_5.addWidget(self.karmaUsernameEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.installedBtn = QtGui.QPushButton(self.groupBox)
        self.installedBtn.setCheckable(True)
        self.installedBtn.setChecked(True)
        self.installedBtn.setAutoDefault(False)
        self.installedBtn.setDefault(False)
        self.installedBtn.setFlat(False)
        self.installedBtn.setObjectName("installedBtn")
        self.horizontalLayout.addWidget(self.installedBtn)
        self.availableBtn = QtGui.QPushButton(self.groupBox)
        self.availableBtn.setCheckable(True)
        self.availableBtn.setChecked(False)
        self.availableBtn.setAutoDefault(False)
        self.availableBtn.setDefault(False)
        self.availableBtn.setFlat(False)
        self.availableBtn.setObjectName("availableBtn")
        self.horizontalLayout.addWidget(self.availableBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.pkgList = QtGui.QListWidget(self.pkgLists)
        self.pkgList.setFrameShadow(QtGui.QFrame.Sunken)
        self.pkgList.setTabKeyNavigation(False)
        self.pkgList.setObjectName("pkgList")
        self.verticalLayout.addWidget(self.pkgList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.pkgLists)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.maxDays = QtGui.QSpinBox(self.pkgLists)
        self.maxDays.setSuffix("")
        self.maxDays.setPrefix("")
        self.maxDays.setMinimum(1)
        self.maxDays.setMaximum(99999)
        self.maxDays.setProperty("value", 7)
        self.maxDays.setObjectName("maxDays")
        self.horizontalLayout_3.addWidget(self.maxDays)
        self.label_5 = QtGui.QLabel(self.pkgLists)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.releaseComboBox = QtGui.QComboBox(self.pkgLists)
        self.releaseComboBox.setObjectName("releaseComboBox")
        self.horizontalLayout_5.addWidget(self.releaseComboBox)
        self.loadPackagesBtn = QtGui.QPushButton(self.pkgLists)
        self.loadPackagesBtn.setObjectName("loadPackagesBtn")
        self.horizontalLayout_5.addWidget(self.loadPackagesBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.pkgLists)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(9000, 9000))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tabWhatToTest = QtGui.QWidget()
        self.tabWhatToTest.setAutoFillBackground(False)
        self.tabWhatToTest.setStyleSheet("")
        self.tabWhatToTest.setObjectName("tabWhatToTest")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabWhatToTest)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.toolBoxWhatToTest = QtGui.QToolBox(self.tabWhatToTest)
        self.toolBoxWhatToTest.setObjectName("toolBoxWhatToTest")
        self.toolBoxWelcome = QtGui.QWidget()
        self.toolBoxWelcome.setObjectName("toolBoxWelcome")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.toolBoxWelcome)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.textBrowser_2 = QtGui.QTextBrowser(self.toolBoxWelcome)
        self.textBrowser_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textBrowser_2.setFrameShadow(QtGui.QFrame.Plain)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_7.addWidget(self.textBrowser_2)
        self.toolBoxWhatToTest.addItem(self.toolBoxWelcome, "")
        self.toolBoxNegativeKarma = QtGui.QWidget()
        self.toolBoxNegativeKarma.setGeometry(QtCore.QRect(0, 0, 712, 424))
        self.toolBoxNegativeKarma.setObjectName("toolBoxNegativeKarma")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.toolBoxNegativeKarma)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtGui.QLabel(self.toolBoxNegativeKarma)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.treeWidget_negative_karma = QtGui.QTreeWidget(self.toolBoxNegativeKarma)
        self.treeWidget_negative_karma.setObjectName("treeWidget_negative_karma")
        self.verticalLayout_9.addWidget(self.treeWidget_negative_karma)
        self.toolBoxWhatToTest.addItem(self.toolBoxNegativeKarma, "")
        self.toolBoxRunning = QtGui.QWidget()
        self.toolBoxRunning.setObjectName("toolBoxRunning")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.toolBoxRunning)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.toolBoxWhatToTest.addItem(self.toolBoxRunning, "")
        self.toolBoxFavorite = QtGui.QWidget()
        self.toolBoxFavorite.setObjectName("toolBoxFavorite")
        self.toolBoxWhatToTest.addItem(self.toolBoxFavorite, "")
        self.verticalLayout_8.addWidget(self.toolBoxWhatToTest)
        self.tabWidget.addTab(self.tabWhatToTest, "")
        self.TabInfo = QtGui.QWidget()
        self.TabInfo.setCursor(QtCore.Qt.ArrowCursor)
        self.TabInfo.setStyleSheet("")
        self.TabInfo.setObjectName("TabInfo")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.TabInfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_2 = QtGui.QTabWidget(self.TabInfo)
        self.tabWidget_2.setTabPosition(QtGui.QTabWidget.East)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabPkg_info = QtGui.QWidget()
        self.tabPkg_info.setObjectName("tabPkg_info")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabPkg_info)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_6 = QtGui.QSplitter(self.tabPkg_info)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_7 = QtGui.QSplitter(self.splitter_6)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.layoutWidget_2 = QtGui.QWidget(self.splitter_7)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pkgNameLabel = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pkgNameLabel.setFont(font)
        self.pkgNameLabel.setCursor(QtCore.Qt.ArrowCursor)
        self.pkgNameLabel.setMouseTracking(False)
        self.pkgNameLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pkgNameLabel.setAcceptDrops(False)
        self.pkgNameLabel.setObjectName("pkgNameLabel")
        self.verticalLayout_11.addWidget(self.pkgNameLabel)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_11.addWidget(self.textBrowser)
        self.splitter_8 = QtGui.QSplitter(self.splitter_7)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.treeWidget_bugs = QtGui.QTreeWidget(self.splitter_8)
        self.treeWidget_bugs.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.treeWidget_bugs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget_bugs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget_bugs.setRootIsDecorated(False)
        self.treeWidget_bugs.setWordWrap(False)
        self.treeWidget_bugs.setColumnCount(2)
        self.treeWidget_bugs.setObjectName("treeWidget_bugs")
        self.treeWidget_test_cases = QtGui.QTreeWidget(self.splitter_8)
        self.treeWidget_test_cases.setRootIsDecorated(False)
        self.treeWidget_test_cases.setObjectName("treeWidget_test_cases")
        self.treeWidget_related_packages = QtGui.QTreeWidget(self.splitter_8)
        self.treeWidget_related_packages.setObjectName("treeWidget_related_packages")
        self.treeWidget_feedback = QtGui.QTreeWidget(self.splitter_6)
        self.treeWidget_feedback.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget_feedback.setRootIsDecorated(False)
        self.treeWidget_feedback.setUniformRowHeights(False)
        self.treeWidget_feedback.setObjectName("treeWidget_feedback")
        self.treeWidget_feedback.header().setCascadingSectionResizes(False)
        self.treeWidget_feedback.header().setMinimumSectionSize(30)
        self.verticalLayout_6.addWidget(self.splitter_6)
        self.tabWidget_2.addTab(self.tabPkg_info, "")
        self.tabPkg_karma = QtGui.QWidget()
        self.tabPkg_karma.setObjectName("tabPkg_karma")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tabPkg_karma)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.tabPkg_karma)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.usernameEdit = QtGui.QLineEdit(self.tabPkg_karma)
        self.usernameEdit.setObjectName("usernameEdit")
        self.horizontalLayout_8.addWidget(self.usernameEdit)
        self.passwordEdit = QtGui.QLineEdit(self.tabPkg_karma)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_8.addWidget(self.passwordEdit)
        self.karmaBox = QtGui.QComboBox(self.tabPkg_karma)
        self.karmaBox.setObjectName("karmaBox")
        self.karmaBox.addItem("")
        self.karmaBox.addItem("")
        self.karmaBox.addItem("")
        self.horizontalLayout_8.addWidget(self.karmaBox)
        self.sendBtn = QtGui.QPushButton(self.tabPkg_karma)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout_8.addWidget(self.sendBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.label_2 = QtGui.QLabel(self.tabPkg_karma)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.commentEdit = QtGui.QPlainTextEdit(self.tabPkg_karma)
        self.commentEdit.setObjectName("commentEdit")
        self.verticalLayout_2.addWidget(self.commentEdit)
        self.label_3 = QtGui.QLabel(self.tabPkg_karma)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.textHints = QtGui.QTextBrowser(self.tabPkg_karma)
        self.textHints.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textHints.sizePolicy().hasHeightForWidth())
        self.textHints.setSizePolicy(sizePolicy)
        self.textHints.setAutoFillBackground(True)
        self.textHints.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textHints.setFrameShape(QtGui.QFrame.NoFrame)
        self.textHints.setFrameShadow(QtGui.QFrame.Plain)
        self.textHints.setObjectName("textHints")
        self.verticalLayout_2.addWidget(self.textHints)
        self.verticalLayout_14.addLayout(self.verticalLayout_2)
        self.tabWidget_2.addTab(self.tabPkg_karma, "")
        self.tabPkg_settings = QtGui.QWidget()
        self.tabPkg_settings.setObjectName("tabPkg_settings")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabPkg_settings)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtGui.QLabel(self.tabPkg_settings)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_7)
        self.radioButton = QtGui.QRadioButton(self.tabPkg_settings)
        self.radioButton.setObjectName("radioButton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.tabPkg_settings)
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.radioButton_2)
        self.radioButton_3 = QtGui.QRadioButton(self.tabPkg_settings)
        self.radioButton_3.setObjectName("radioButton_3")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.radioButton_3)
        self.pkg_settings_open_bodhi_update = QtGui.QPushButton(self.tabPkg_settings)
        self.pkg_settings_open_bodhi_update.setObjectName("pkg_settings_open_bodhi_update")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.pkg_settings_open_bodhi_update)
        self.pkg_settings_download_source_rpm = QtGui.QPushButton(self.tabPkg_settings)
        self.pkg_settings_download_source_rpm.setObjectName("pkg_settings_download_source_rpm")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pkg_settings_download_source_rpm)
        self.label_8 = QtGui.QLabel(self.tabPkg_settings)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.verticalLayout_10.addLayout(self.formLayout)
        self.tabWidget_2.addTab(self.tabPkg_settings, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.TabInfo, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.statusList = QtGui.QListWidget(self.splitter_5)
        self.statusList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.statusList.setObjectName("statusList")
        self.verticalLayout_3.addWidget(self.splitter_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.toolBoxWhatToTest.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.karmaBox.setCurrentIndex(1)
        QtCore.QObject.connect(self.karmaCheckBox, QtCore.SIGNAL("toggled(bool)"), self.karmaUsernameEdit.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.karmaBox, self.sendBtn)
        MainWindow.setTabOrder(self.sendBtn, self.loadPackagesBtn)
        MainWindow.setTabOrder(self.loadPackagesBtn, self.availableBtn)
        MainWindow.setTabOrder(self.availableBtn, self.pkgList)
        MainWindow.setTabOrder(self.pkgList, self.releaseComboBox)
        MainWindow.setTabOrder(self.releaseComboBox, self.installedBtn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Fedora Gooey Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.searchEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search packages...", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "karma not submitted by user", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaUsernameEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "username for karma filter", None, QtGui.QApplication.UnicodeUTF8))
        self.installedBtn.setText(QtGui.QApplication.translate("MainWindow", "Installed", None, QtGui.QApplication.UnicodeUTF8))
        self.availableBtn.setText(QtGui.QApplication.translate("MainWindow", "Available", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgList.setSortingEnabled(True)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Updated for last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "days", None, QtGui.QApplication.UnicodeUTF8))
        self.loadPackagesBtn.setText(QtGui.QApplication.translate("MainWindow", "Load Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Welcome to<span style=\" font-weight:600;\"> Fedora Gooey Karma</span> tool which helps you with testing new updates for your Fedora.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To load updates, press lower-left <span style=\" font-weight:600;\">Load packages</span> button. If you are not sure what you should test, wait until all packages are loaded and see sections below this text.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxWhatToTest.setItemText(self.toolBoxWhatToTest.indexOf(self.toolBoxWelcome), QtGui.QApplication.translate("MainWindow", "Fedora Gooey Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "It would be nice to re-test updates which has got negative karma. See these packages below.", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_negative_karma.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", " ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxWhatToTest.setItemText(self.toolBoxWhatToTest.indexOf(self.toolBoxNegativeKarma), QtGui.QApplication.translate("MainWindow", "Updates with negative karma", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxWhatToTest.setItemText(self.toolBoxWhatToTest.indexOf(self.toolBoxRunning), QtGui.QApplication.translate("MainWindow", "Currently running applications", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBoxWhatToTest.setItemText(self.toolBoxWhatToTest.indexOf(self.toolBoxFavorite), QtGui.QApplication.translate("MainWindow", "Favorite packages", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWhatToTest), QtGui.QApplication.translate("MainWindow", "What to test", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Package name", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_bugs.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Bug id", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_bugs.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_test_cases.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Test cases", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_related_packages.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Related packages", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.setSortingEnabled(True)
        self.treeWidget_feedback.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabPkg_info), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "FAS credentials", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "username", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "password", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBtn.setText(QtGui.QApplication.translate("MainWindow", "Send Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Your comment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Hints", None, QtGui.QApplication.UnicodeUTF8))
        self.textHints.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Have you tried attached <span style=\" font-weight:600;\">test cases</span>?</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Have you taken a look at <span style=\" font-weight:600;\">bugs</span>?</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want to give <span style=\" font-weight:600;\">negative</span> karma - are you sure that<span style=\" font-weight:600;\"> this component</span> makes <span style=\" font-weight:600;\">problems</span>?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabPkg_karma), QtGui.QApplication.translate("MainWindow", "Add karma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Package category", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Normal package", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Favorite package", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Ignore this package", None, QtGui.QApplication.UnicodeUTF8))
        self.pkg_settings_open_bodhi_update.setText(QtGui.QApplication.translate("MainWindow", "Open bodhi update in web browser", None, QtGui.QApplication.UnicodeUTF8))
        self.pkg_settings_download_source_rpm.setText(QtGui.QApplication.translate("MainWindow", "Download source RPM", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabPkg_settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabInfo), QtGui.QApplication.translate("MainWindow", "Package info", None, QtGui.QApplication.UnicodeUTF8))
        self.statusList.setSortingEnabled(False)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About Fedora Gooey Karma", None, QtGui.QApplication.UnicodeUTF8))

