# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created: Thu Jun 27 15:44:15 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 772)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_5 = QtGui.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.layoutWidget = QtGui.QWidget(self.splitter_5)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pkgLists = QtGui.QWidget(self.layoutWidget)
        self.pkgLists.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pkgLists.setObjectName("pkgLists")
        self.verticalLayout = QtGui.QVBoxLayout(self.pkgLists)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.pkgLists)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.searchEdit = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.searchEdit.setFont(font)
        self.searchEdit.setInputMask("")
        self.searchEdit.setText("")
        self.searchEdit.setObjectName("searchEdit")
        self.verticalLayout_5.addWidget(self.searchEdit)
        self.karmaCheckBox = QtGui.QCheckBox(self.groupBox)
        self.karmaCheckBox.setObjectName("karmaCheckBox")
        self.verticalLayout_5.addWidget(self.karmaCheckBox)
        self.karmaUsernameEdit = QtGui.QLineEdit(self.groupBox)
        self.karmaUsernameEdit.setDragEnabled(False)
        self.karmaUsernameEdit.setObjectName("karmaUsernameEdit")
        self.verticalLayout_5.addWidget(self.karmaUsernameEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.installedBtn = QtGui.QPushButton(self.groupBox)
        self.installedBtn.setCheckable(True)
        self.installedBtn.setChecked(True)
        self.installedBtn.setAutoDefault(False)
        self.installedBtn.setDefault(False)
        self.installedBtn.setFlat(False)
        self.installedBtn.setObjectName("installedBtn")
        self.horizontalLayout.addWidget(self.installedBtn)
        self.availableBtn = QtGui.QPushButton(self.groupBox)
        self.availableBtn.setCheckable(True)
        self.availableBtn.setChecked(False)
        self.availableBtn.setAutoDefault(False)
        self.availableBtn.setDefault(False)
        self.availableBtn.setFlat(False)
        self.availableBtn.setObjectName("availableBtn")
        self.horizontalLayout.addWidget(self.availableBtn)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.pkgList = QtGui.QListWidget(self.pkgLists)
        self.pkgList.setFrameShadow(QtGui.QFrame.Sunken)
        self.pkgList.setTabKeyNavigation(False)
        self.pkgList.setObjectName("pkgList")
        self.verticalLayout.addWidget(self.pkgList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.pkgLists)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.maxDays = QtGui.QSpinBox(self.pkgLists)
        self.maxDays.setSuffix("")
        self.maxDays.setPrefix("")
        self.maxDays.setMinimum(1)
        self.maxDays.setMaximum(99999)
        self.maxDays.setProperty("value", 7)
        self.maxDays.setObjectName("maxDays")
        self.horizontalLayout_3.addWidget(self.maxDays)
        self.label_5 = QtGui.QLabel(self.pkgLists)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.releaseComboBox = QtGui.QComboBox(self.pkgLists)
        self.releaseComboBox.setObjectName("releaseComboBox")
        self.horizontalLayout_5.addWidget(self.releaseComboBox)
        self.loadPackagesBtn = QtGui.QPushButton(self.pkgLists)
        self.loadPackagesBtn.setObjectName("loadPackagesBtn")
        self.horizontalLayout_5.addWidget(self.loadPackagesBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.pkgLists)
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(9000, 9000))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName("tabWidget")
        self.TabInfo = QtGui.QWidget()
        self.TabInfo.setCursor(QtCore.Qt.ArrowCursor)
        self.TabInfo.setObjectName("TabInfo")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.TabInfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_4 = QtGui.QSplitter(self.TabInfo)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter_3 = QtGui.QSplitter(self.splitter_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget1 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pkgNameLabel = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pkgNameLabel.setFont(font)
        self.pkgNameLabel.setCursor(QtCore.Qt.ArrowCursor)
        self.pkgNameLabel.setMouseTracking(False)
        self.pkgNameLabel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pkgNameLabel.setAcceptDrops(False)
        self.pkgNameLabel.setObjectName("pkgNameLabel")
        self.verticalLayout_2.addWidget(self.pkgNameLabel)
        self.textBrowser = QtGui.QTextBrowser(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.treeWidget_bugs = QtGui.QTreeWidget(self.splitter_2)
        self.treeWidget_bugs.setProperty("cursor", QtCore.Qt.ArrowCursor)
        self.treeWidget_bugs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget_bugs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget_bugs.setRootIsDecorated(False)
        self.treeWidget_bugs.setWordWrap(False)
        self.treeWidget_bugs.setColumnCount(2)
        self.treeWidget_bugs.setObjectName("treeWidget_bugs")
        self.treeWidget_test_cases = QtGui.QTreeWidget(self.splitter_2)
        self.treeWidget_test_cases.setRootIsDecorated(False)
        self.treeWidget_test_cases.setObjectName("treeWidget_test_cases")
        self.treeWidget_related_packages = QtGui.QTreeWidget(self.splitter_2)
        self.treeWidget_related_packages.setObjectName("treeWidget_related_packages")
        self.treeWidget_feedback = QtGui.QTreeWidget(self.splitter_4)
        self.treeWidget_feedback.setMinimumSize(QtCore.QSize(0, 0))
        self.treeWidget_feedback.setRootIsDecorated(False)
        self.treeWidget_feedback.setUniformRowHeights(False)
        self.treeWidget_feedback.setObjectName("treeWidget_feedback")
        self.treeWidget_feedback.header().setCascadingSectionResizes(False)
        self.treeWidget_feedback.header().setMinimumSectionSize(30)
        self.verticalLayout_4.addWidget(self.splitter_4)
        self.tabWidget.addTab(self.TabInfo, "")
        self.TabComment = QtGui.QWidget()
        self.TabComment.setObjectName("TabComment")
        self.gridLayout_2 = QtGui.QGridLayout(self.TabComment)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtGui.QWidget(self.TabComment)
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.usernameEdit = QtGui.QLineEdit(self.widget)
        self.usernameEdit.setObjectName("usernameEdit")
        self.horizontalLayout_8.addWidget(self.usernameEdit)
        self.passwordEdit = QtGui.QLineEdit(self.widget)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_8.addWidget(self.passwordEdit)
        self.karmaBox = QtGui.QComboBox(self.widget)
        self.karmaBox.setObjectName("karmaBox")
        self.karmaBox.addItem("")
        self.karmaBox.addItem("")
        self.karmaBox.addItem("")
        self.horizontalLayout_8.addWidget(self.karmaBox)
        self.sendBtn = QtGui.QPushButton(self.widget)
        self.sendBtn.setObjectName("sendBtn")
        self.horizontalLayout_8.addWidget(self.sendBtn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.TabComment)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.commentEdit = QtGui.QPlainTextEdit(self.TabComment)
        self.commentEdit.setObjectName("commentEdit")
        self.gridLayout_2.addWidget(self.commentEdit, 1, 0, 1, 1)
        self.textHints = QtGui.QTextBrowser(self.TabComment)
        self.textHints.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textHints.sizePolicy().hasHeightForWidth())
        self.textHints.setSizePolicy(sizePolicy)
        self.textHints.setAutoFillBackground(True)
        self.textHints.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.textHints.setFrameShape(QtGui.QFrame.NoFrame)
        self.textHints.setFrameShadow(QtGui.QFrame.Plain)
        self.textHints.setObjectName("textHints")
        self.gridLayout_2.addWidget(self.textHints, 3, 0, 1, 1)
        self.tabWidget.addTab(self.TabComment, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.statusList = QtGui.QListWidget(self.splitter_5)
        self.statusList.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.statusList.setObjectName("statusList")
        self.verticalLayout_3.addWidget(self.splitter_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1002, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.karmaBox.setCurrentIndex(1)
        QtCore.QObject.connect(self.karmaCheckBox, QtCore.SIGNAL("toggled(bool)"), self.karmaUsernameEdit.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.karmaBox, self.commentEdit)
        MainWindow.setTabOrder(self.commentEdit, self.sendBtn)
        MainWindow.setTabOrder(self.sendBtn, self.textHints)
        MainWindow.setTabOrder(self.textHints, self.loadPackagesBtn)
        MainWindow.setTabOrder(self.loadPackagesBtn, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.treeWidget_bugs)
        MainWindow.setTabOrder(self.treeWidget_bugs, self.treeWidget_test_cases)
        MainWindow.setTabOrder(self.treeWidget_test_cases, self.treeWidget_related_packages)
        MainWindow.setTabOrder(self.treeWidget_related_packages, self.treeWidget_feedback)
        MainWindow.setTabOrder(self.treeWidget_feedback, self.availableBtn)
        MainWindow.setTabOrder(self.availableBtn, self.pkgList)
        MainWindow.setTabOrder(self.pkgList, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.releaseComboBox)
        MainWindow.setTabOrder(self.releaseComboBox, self.installedBtn)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Fedora Gooey Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.searchEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search packages...", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaCheckBox.setText(QtGui.QApplication.translate("MainWindow", "karma not submitted by user", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaUsernameEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "username for karma filter", None, QtGui.QApplication.UnicodeUTF8))
        self.installedBtn.setText(QtGui.QApplication.translate("MainWindow", "Installed", None, QtGui.QApplication.UnicodeUTF8))
        self.availableBtn.setText(QtGui.QApplication.translate("MainWindow", "Available", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgList.setSortingEnabled(True)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Updated for last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "days", None, QtGui.QApplication.UnicodeUTF8))
        self.loadPackagesBtn.setText(QtGui.QApplication.translate("MainWindow", "Load Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.pkgNameLabel.setText(QtGui.QApplication.translate("MainWindow", "Package name", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monospace\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_bugs.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Bug id", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_bugs.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_test_cases.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Test cases", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_related_packages.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Related packages", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.setSortingEnabled(True)
        self.treeWidget_feedback.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.headerItem().setText(2, QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_feedback.headerItem().setText(3, QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabInfo), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "FAS credentials", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "username", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "password", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.karmaBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.sendBtn.setText(QtGui.QApplication.translate("MainWindow", "Send Karma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Your comment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Hints", None, QtGui.QApplication.UnicodeUTF8))
        self.textHints.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Have you tried attached <span style=\" font-weight:600;\">test cases</span>?</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Have you taken a look at <span style=\" font-weight:600;\">bugs</span>?</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you want to give <span style=\" font-weight:600;\">negative</span> karma - are you sure that<span style=\" font-weight:600;\"> this component</span> makes <span style=\" font-weight:600;\">problems</span>?</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabComment), QtGui.QApplication.translate("MainWindow", "Add comment and karma", None, QtGui.QApplication.UnicodeUTF8))
        self.statusList.setSortingEnabled(False)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About Fedora Gooey Karma", None, QtGui.QApplication.UnicodeUTF8))

